"""initial schema

Revision ID: 9c03bf3b0d52
Revises: 
Create Date: 2026-09-17 20:11:54.516480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c03bf3b0d52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activity_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('egfr', sa.Float(), nullable=True),
    sa.Column('salt_limit_g', sa.Float(), nullable=False),
    sa.Column('protein_limit_g', sa.Float(), nullable=False),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meal_slots', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dish_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('protein_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('salt_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_normalized_name'), 'recipe', ['normalized_name'], unique=False)
    op.create_table('weekly_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calorie_target_kcal', sa.Float(), nullable=False),
    sa.Column('calorie_target_min', sa.Float(), nullable=False),
    sa.Column('calorie_target_max', sa.Float(), nullable=False),
    sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_summary_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_menu_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('breakfast_recipe_id', sa.Integer(), nullable=False),
    sa.Column('lunch_recipe_id', sa.Integer(), nullable=False),
    sa.Column('dinner_recipe_id', sa.Integer(), nullable=False),
    sa.Column('meals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_calories_kcal', sa.Float(), nullable=False),
    sa.Column('total_protein_g', sa.Float(), nullable=False),
    sa.Column('total_salt_g', sa.Float(), nullable=False),
    sa.Column('total_fat_g', sa.Float(), nullable=False),
    sa.Column('total_carbs_g', sa.Float(), nullable=False),
    sa.Column('adjustment_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['breakfast_recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['dinner_recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['lunch_recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['weekly_menu_id'], ['weekly_menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_menu_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=True),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['weekly_menu_id'], ['weekly_menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_warnings')
    op.drop_table('menu_days')
    op.drop_table('weekly_menus')
    op.drop_index(op.f('ix_recipe_normalized_name'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_table('profile')
    op.drop_table('preference')
    # ### end Alembic commands ###
